#!/usr/bin/env python3

import os
import argparse
import sys
import time

from multiprocessing import cpu_count
from multiprocessing.pool import Pool
from path import Path
from pygount import SourceAnalysis
from dataclasses import dataclass
from typing import Dict, Union

verbose = False

def log(message):
    global verbose
    if verbose:
        sys.stderr.write(message + "\n")

def file_list():
    for source_path in sys.stdin:
        source_path = source_path.strip()
        log(f"Parsing {source_path}")

        if not os.path.isfile(source_path):
            log(f"Ignoring {source_path}: not a file")
            continue

        yield source_path

def process_source(source_path):
    return (source_path, SourceAnalysis.from_file(source_path, "").code_count)

@dataclass
class File:
    name: str
    size: int

    def as_dict(self):
        return {"name": self.name, "size": self.size}

    def as_ncdu(self):
        return {
            "name": self.name,
            "asize": self.size,
            "dsize": self.size
        }

@dataclass
class Directory:
    name: str
    entries: Dict[str, Union[File, "Directory"]]

    def record(self, path: Path, size):
        parts = path.parts()[1:]
        name = parts[0]
        rest = parts[1:]
        if len(parts) == 1:
            self.entries[name] = File(name=name, size=size)
        else:
            if name not in self.entries:
                self.entries[parts[0]] = Directory(name=name, entries={})
            self.entries[name].record(Path(os.path.join(*rest)), size)

    def as_dict(self):
        return {
            "name": self.name,
            "entries": {
                name: entry.as_dict()
                for name, entry
                in self.entries.items()
            }
        }

    def as_ncdu(self):
        return [
            {
                "name": self.name,
                "asize": 0,
                "dsize": 0
            }
        ] + [entry.as_ncdu() for entry in self.entries.values()]

def main():
    parser = argparse.ArgumentParser(description=".")
    parser.add_argument("--verbose", action="store_true", help="Emit log info.")
    parser.add_argument("-j",
                        metavar="JOBS",
                        dest="jobs",
                        default=0,
                        type=int,
                        help="Emit log info.")
    args = parser.parse_args()

    global verbose
    verbose = args.verbose

    jobs = args.jobs
    if jobs == 0:
        jobs = cpu_count()

    pool = Pool(jobs)

    root = Directory(name="/", entries={})
    for source_path, size in pool.imap(process_source, file_list()):
        root.record(Path(source_path), size)

    import json
    print(json.dumps([
        1,
        2,
        {
            "progname": "slocncdu",
            "progver": "1.0",
            "timestamp": int(time.time())
        },
        root.as_ncdu()
    ], indent=2))

    return 0

if __name__ == "__main__":
    sys.exit(main())
